# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    servlet:
      path: /moria


spring:
  profiles:
  # 环境 dev|test|pro
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: moria
  mvc:
    static-path-pattern: /resources/**
#    prefer-ip-address: true



# Mybatis配置 如果用下面的试可以此处屏蔽
#mybatis:
#    mapperLocations: classpath:mapper/**/*.xml
#    typeAliasesPackage: com.forveross.*.entity
#    configLocation: classpath:mybatis.xml


#mybatis-plus 如果引入了mybatis-plus包，用下面的方式
##mybatis-plus官网http://mp.baomidou.com/
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  config-locations: classpath:mybatis.xml
#  typeAliasesPackage: com.yourpackage.*.entity
  #@groupId@是利用spring boot占位符获取pom.xml里中groupId的值
#  typeAliasesPackage: com.forveross.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
#    meta-object-handler: com.forveross.common.mybatis.CustomMetaObjectHandler
    #自定义SQL注入器
#    sql-injector: com.forveross.common.mybatis.CustomSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    logPrefix: dao.
